export * from './studentRegisterRequest.dto'
export * from './studentRegisterResponse.dto'
export * from './studentLoginRequest.dto'
export * from './studentGetAllResponse.dto'
export * from './studentGetByIdResponse.dto'
