export * from './create/academicYearCreateController'
export * from './getAll/academicYearGetAllController'
export * from './getById/academicYearGetByIdController'
export * from './update/AcademicYearUpdateController'
export * from './delete/academicYearDeleteController'
