export const AdminGetAllResponseDTO = [
  {
    id: '1234',
    name: 'User Name',
    email: 'user@email.com',
    role: 'admin',
    academicTerms: [],
    academicYears: [],
    classLevels: [],
    programs: [],
    students: [],
    teachers: [],
    yearGroups: [],
  },
  {
    id: '4567',
    name: 'User Name 2',
    email: 'user_2@email.com',
    role: 'admin',
    academicTerms: [],
    academicYears: [],
    classLevels: [],
    programs: [],
    students: [],
    teachers: [],
    yearGroups: [],
  },
]
