export * from './create/academicTermCreateController'
export * from './getAll/academicTermGetAllController'
export * from './getById/academicTermGetByIdController'
export * from './update/academicTermUpdateController'
export * from './delete/academicTermDeleteController'
